### ISSUE TITLE
setting referenceItemIdx

### ISSUE THREAD

**Issue by jhvital** [usnistgov/OpenSeadragonScalebar#18]
Hi!

When setting the variable _referenceItemIdx_ like below:

```
 viewer.scalebar({
      pixelsPerMeter: 2710000,
      referenceItemIdx: 8,
      color:"rgb(150, 150, 150)",
      fontColor:"rgb(100,100,100)",
      backgroundColor:"rgba(255, 255, 255, 0.5)",
      barThickness: 2
    });
```
I get the following error.
I tried with openseadragon 4.1 and 2.1.0 with the same result.

```
openseadragon-scalebar.js:479  Uncaught TypeError: Cannot read properties of undefined (reading '_scaleSpring')
    at tiledImageViewportToImageZoom (openseadragon-scalebar.js:479:32)
    at $.Scalebar.refresh (openseadragon-scalebar.js:247:24)
    at Object.handler (openseadragon-scalebar.js:121:18)
    at openseadragon.js:2995:33
    at a.Viewer.raiseEvent (openseadragon.js:3017:13)
    at i (openseadragon.js:7276:27)
    at b.success (openseadragon.js:7328:17)
    at openseadragon.js:8085:39
    at a.TileSource.success (openseadragon.js:8778:21)
    at Object.handler (openseadragon.js:10846:19)
```
I'm declaring the viewer like so:

```
var viewer = OpenSeadragon({
    id: 'openseadragon-viewer',
    prefixUrl: 'https://cdn.jsdelivr.net/npm/openseadragon@4.1/build/openseadragon/images/',
    // minLevel:8,
    showNavigator:true
});
```

Any idea why this might be happening?
Thank you.

**Comment by KARTHI2710** [comment]
actually it works
                viewer.scalebar({
                    pixelsPerMeter: 5.16,
                    color:"black",
                    fontColor:"black",
                    fontSize:"15px",
                    minWidth:"60px",
                    // backgroundColor:rgba(255, 255, 255, 0.5),
                    barThickness: 2
                });   use this
